import type { Prisma } from '../src/generated';

// Sourced directly from INDICATORS_CATALOG.md.
// Codes are stable — never reuse a code.
// Add new indicators by appending; never change existing codes.

export const INDICATOR_SEEDS: Prisma.IndicatorCreateManyInput[] = [
  // ── Framework 1: LWEP agreed 22-indicator minimum set ──────────────────────

  // Representation
  {
    code: 'BPfA-REP-001',
    name: 'Percentage of seats held by women in national parliament',
    description:
      'Share of seats in the national parliament occupied by women.',
    framework: 'BPFA',
    area: 'Representation',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'IPU / UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-REP-002',
    name: 'Percentage of women in ministerial positions',
    description: 'Share of ministerial cabinet positions held by women.',
    framework: 'BPFA',
    area: 'Representation',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-REP-003',
    name: 'Percentage of women in leadership positions in media organisations',
    description: 'Share of leadership and editorial positions in media held by women.',
    framework: 'BPFA',
    area: 'Representation',
    unit: '%',
    periodicity: 'BIENNIAL',
    disaggregations: [],
    custodianAgency: 'MOGCSP',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-REP-004',
    name: 'Percentage of women in local councils or leadership positions in municipalities',
    description: 'Share of local government council seats held by women.',
    framework: 'BPFA',
    area: 'Representation',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'MOGCSP',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-REP-005',
    name: 'Percentage of women leaders in civil-society organisations',
    description: 'Share of leadership roles in registered CSOs held by women.',
    framework: 'BPFA',
    area: 'Representation',
    unit: '%',
    periodicity: 'BIENNIAL',
    disaggregations: [],
    custodianAgency: 'MOGCSP',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // Education
  {
    code: 'BPfA-EDU-001',
    name: 'Net enrolment rate for girls in primary education',
    description: 'Proportion of girls of official primary school age who are enrolled in primary school.',
    framework: 'BPFA',
    area: 'Education',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'UIS / UNESCO',
    leadMinistry: 'MoE',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-EDU-002',
    name: 'Percentage of girls completing secondary education',
    description: 'Proportion of girls who complete the final grade of secondary school.',
    framework: 'BPFA',
    area: 'Education',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'UIS / UNESCO',
    leadMinistry: 'MoE',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-EDU-003',
    name: 'Adult female literacy rate',
    description: 'Percentage of women aged 15+ who can read and write.',
    framework: 'BPFA',
    area: 'Education',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['AGE', 'LOCATION'],
    custodianAgency: 'UIS / UNESCO',
    leadMinistry: 'MoE',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-EDU-004',
    name: 'Percentage of women enrolled in STEM programs in tertiary education',
    description: 'Share of women among students enrolled in STEM fields in universities and colleges.',
    framework: 'BPFA',
    area: 'Education',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'UIS / UNESCO',
    leadMinistry: 'MoE',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // Work
  {
    code: 'BPfA-WRK-001',
    name: 'Female labour-force participation rate',
    description: 'Proportion of women aged 15+ who are employed or actively seeking employment.',
    framework: 'BPFA',
    area: 'Work',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['AGE', 'LOCATION'],
    custodianAgency: 'ILO',
    leadMinistry: 'MoL',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-WRK-002',
    name: 'Gender wage gap',
    description: 'Difference between male and female median wages as a percentage of male wages.',
    framework: 'BPFA',
    area: 'Work',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['AGE'],
    custodianAgency: 'ILO',
    leadMinistry: 'MoL',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // Health
  {
    code: 'BPfA-HLT-001',
    name: 'Maternal mortality ratio',
    description: 'Number of maternal deaths per 100,000 live births.',
    framework: 'BPFA',
    area: 'Health',
    unit: 'per 100,000 live births',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'WHO / UNICEF / UNFPA',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-HLT-002',
    name: 'Contraceptive prevalence rate (modern methods)',
    description: 'Proportion of women of reproductive age (15–49) using modern contraceptive methods.',
    framework: 'BPFA',
    area: 'Health',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['AGE', 'LOCATION'],
    custodianAgency: 'UNPD / UNFPA',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-HLT-003',
    name: 'Percentage of women aged 20–24 married before age 18',
    description: 'Share of women aged 20–24 who were first married or in union before age 18.',
    framework: 'BPFA',
    area: 'Health',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['LOCATION'],
    custodianAgency: 'UNICEF',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // Violence (GBV)
  {
    code: 'BPfA-GBV-001',
    name: 'Prevalence of physical or sexual violence against women',
    description: 'Proportion of women who have experienced physical or sexual violence in the last 12 months.',
    framework: 'BPFA',
    area: 'Violence',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['AGE', 'LOCATION'],
    custodianAgency: 'WHO / UNSD / UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // WASH
  {
    code: 'BPfA-WSH-001',
    name: 'Percentage of women with access to safe drinking water and improved sanitation facilities',
    description: 'Share of women in households with access to safely managed water and sanitation.',
    framework: 'BPFA',
    area: 'WASH',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'WHO / UNICEF JMP',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // Agriculture & Environment
  {
    code: 'BPfA-AGR-001',
    name: 'Percentage of women with land ownership rights',
    description: 'Share of women among agricultural land owners or rights-bearers.',
    framework: 'BPFA',
    area: 'Agriculture',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'FAO',
    leadMinistry: 'MoA',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-AGR-002',
    name: 'Percentage of women involved in decision-making in agricultural cooperatives',
    description: 'Share of women in leadership or decision-making roles in registered agricultural cooperatives.',
    framework: 'BPFA',
    area: 'Agriculture',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'FAO',
    leadMinistry: 'MoA',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'BPfA-ENV-001',
    name: 'Percentage of women involved in environmental conservation programs',
    description: 'Share of women participating in government and NGO-led environmental conservation programs.',
    framework: 'BPFA',
    area: 'Environment',
    unit: '%',
    periodicity: 'BIENNIAL',
    disaggregations: [],
    custodianAgency: 'MOGCSP',
    leadMinistry: 'MoA',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // Security
  {
    code: 'BPfA-SEC-001',
    name: 'Percentage of women in military or police peacekeeping forces',
    description: 'Share of women among uniformed peacekeeping personnel.',
    framework: 'BPFA',
    area: 'Security',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'UNODC',
    leadMinistry: 'MoJ',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // Maputo Protocol additions
  {
    code: 'MAPUTO-REP-001',
    name: 'Percentage of women in national parliament (Maputo reporting frame)',
    description: 'Women\'s representation in the national parliament — per Maputo Protocol reporting framework.',
    framework: 'MAPUTO',
    area: 'Representation',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'AU / UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'MAPUTO-DM-001',
    name: 'Percentage of women in senior or decision-making positions (public or private sector)',
    description: 'Share of women in senior management or decision-making roles across sectors.',
    framework: 'MAPUTO',
    area: 'Representation',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // ── Framework 2: UN Minimum Set (Theme I — Economy) ─────────────────────────

  {
    code: 'UNMIN-I-01',
    name: 'Average hours spent on unpaid domestic and care work, by sex, age, location',
    description: 'Mean daily hours spent on unpaid domestic and care work, disaggregated by sex, age, and location.',
    framework: 'SDG',
    area: 'Economy',
    unit: 'hours/day',
    periodicity: 'EVERY_5Y',
    disaggregations: ['SEX', 'AGE', 'LOCATION'],
    custodianAgency: 'UNSD / UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-I-03',
    name: 'Labour-force participation rate for persons 15–24 and 15+, by sex',
    description: 'Share of the working-age population actively participating in the labour force.',
    framework: 'SDG',
    area: 'Economy',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['SEX', 'AGE'],
    custodianAgency: 'ILO',
    leadMinistry: 'MoL',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-I-08',
    name: 'Unemployment rate, by sex, age, disability',
    description: 'Share of the labour force that is unemployed, disaggregated by sex, age, and disability status.',
    framework: 'SDG',
    area: 'Economy',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['SEX', 'AGE', 'DISABILITY'],
    custodianAgency: 'ILO',
    leadMinistry: 'MoL',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-I-14',
    name: 'Proportion of population below international poverty line, by sex, age, employment, urban/rural',
    description: 'Share of the population living on less than $2.15/day (2017 PPP).',
    framework: 'SDG',
    area: 'Economy',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['SEX', 'AGE', 'LOCATION'],
    custodianAgency: 'ILO / World Bank',
    leadMinistry: 'MFDP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // ── Framework 2: UN Minimum Set (Theme III — Health) ────────────────────────

  {
    code: 'UNMIN-III-01',
    name: 'Proportion of women (15–49) with family-planning needs satisfied with modern methods',
    description: 'Share of women of reproductive age whose need for family planning is met with modern contraceptives.',
    framework: 'SDG',
    area: 'Health',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['AGE', 'LOCATION'],
    custodianAgency: 'UNPD / UNFPA',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-III-02',
    name: 'Under-five mortality rate, by sex',
    description: 'Probability of dying between birth and age 5, per 1,000 live births.',
    framework: 'SDG',
    area: 'Health',
    unit: 'per 1,000 live births',
    periodicity: 'ANNUAL',
    disaggregations: ['SEX'],
    custodianAgency: 'UNICEF / UNPD / WHO',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-III-03',
    name: 'Maternal mortality ratio',
    description: 'Number of maternal deaths per 100,000 live births (UN Minimum Set tracking).',
    framework: 'SDG',
    area: 'Health',
    unit: 'per 100,000 live births',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'WHO / UNICEF / UNFPA',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-III-04',
    name: 'Antenatal care coverage (at least one visit; at least four visits)',
    description: 'Proportion of women who received antenatal care from a skilled provider.',
    framework: 'SDG',
    area: 'Health',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'UNICEF',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-III-05',
    name: 'Proportion of births attended by skilled health personnel',
    description: 'Share of deliveries attended by a skilled birth attendant.',
    framework: 'SDG',
    area: 'Health',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'UNICEF',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // ── Framework 2: UN Minimum Set (Theme IV — Public Life) ────────────────────

  {
    code: 'UNMIN-IV-01',
    name: "Women's share of government ministerial positions",
    description: 'Proportion of government ministerial cabinet positions held by women.',
    framework: 'SDG',
    area: 'Public Life',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-IV-02',
    name: 'Proportion of seats held by women in national parliament and local governments',
    description: 'Share of parliamentary seats held by women — SDG 5.5.1 reporting.',
    framework: 'SDG',
    area: 'Public Life',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'IPU / UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-IV-03',
    name: 'Proportion of women in managerial positions',
    description: 'Share of managerial positions held by women — SDG 5.5.2.',
    framework: 'SDG',
    area: 'Public Life',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'ILO',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // ── Framework 2: UN Minimum Set (Theme V — Human Rights) ────────────────────

  {
    code: 'UNMIN-V-01',
    name: 'Proportion of ever-partnered women (15+) subjected to IPV in last 12 months',
    description: 'Share of women who have experienced physical or sexual intimate partner violence in the past 12 months — SDG 5.2.1.',
    framework: 'SDG',
    area: 'Human Rights',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['AGE'],
    custodianAgency: 'WHO / UNSD / UNICEF / UN Women / UNODC / UNFPA',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-V-03',
    name: 'Proportion of girls/women (15–49) who have undergone FGM/C, by age',
    description: 'Share of women and girls who have undergone female genital mutilation/cutting — SDG 5.3.2.',
    framework: 'SDG',
    area: 'Human Rights',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['AGE'],
    custodianAgency: 'UNICEF',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-V-04',
    name: 'Proportion of women (20–24) married before 15; before 18',
    description: 'Share of women aged 20–24 who were married or in union before age 15 and 18 — SDG 5.3.1.',
    framework: 'SDG',
    area: 'Human Rights',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['LOCATION'],
    custodianAgency: 'UNICEF',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'UNMIN-V-05',
    name: 'Adolescent birth rate (10–14; 15–19) per 1,000 women',
    description: 'Number of births per 1,000 adolescent women — SDG 3.7.2.',
    framework: 'SDG',
    area: 'Human Rights',
    unit: 'per 1,000',
    periodicity: 'ANNUAL',
    disaggregations: ['AGE'],
    custodianAgency: 'UNPD / UNFPA',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // ── Framework 3: AU WPS (selected high-priority) ─────────────────────────────

  {
    code: 'AU-WPS-PA-001',
    name: 'Percentage of women in decision-making positions (AU WPS)',
    description: 'Share of women in ministerial, permanent secretary, and commission head positions — AU WPS Participation pillar.',
    framework: 'AU_WPS',
    area: 'AU-WPS-PARTICIPATION',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'AU / UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'AU-WPS-PA-003',
    name: 'Percentage of women in security institutions (AU WPS)',
    description: 'Share of women in police, justice, military, immigration, intelligence, and prisons — AU WPS Participation pillar.',
    framework: 'AU_WPS',
    area: 'AU-WPS-PARTICIPATION',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'UNODC / AU',
    leadMinistry: 'MoJ',
    formula: null,
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'AU-WPS-PT-002',
    name: 'Number/proportion of GBV cases reported, acted upon, concluded (AU WPS)',
    description: 'Tracking of reported GBV cases through the justice system — AU WPS Protection pillar.',
    framework: 'AU_WPS',
    area: 'AU-WPS-PROTECTION',
    unit: 'count',
    periodicity: 'QUARTERLY',
    disaggregations: ['LOCATION'],
    custodianAgency: 'UNODC / AU',
    leadMinistry: 'MOGCSP',
    formula: 'computeGbvCaseCounts',
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },

  // ── Framework 5: LWEP Project Output Indicators ──────────────────────────────

  {
    code: 'LWEP-OUT-C1-01',
    name: 'Number of communities reached with SASA! social norms engagement',
    description: 'Count of communities that completed at least one SASA! awareness session.',
    framework: 'LWEP',
    area: 'Component 1',
    unit: 'count',
    periodicity: 'QUARTERLY',
    disaggregations: ['LOCATION'],
    custodianAgency: 'MOGCSP PMU',
    leadMinistry: 'MOGCSP',
    formula: 'computeCommunitiesWithSasaSessions',
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'LWEP-OUT-C1-02',
    name: 'Number of community members participating in SASA! sessions, by sex and age',
    description: 'Total attendance across all SASA! sessions, disaggregated by sex and age bracket.',
    framework: 'LWEP',
    area: 'Component 1',
    unit: 'count',
    periodicity: 'QUARTERLY',
    disaggregations: ['SEX', 'AGE', 'LOCATION'],
    custodianAgency: 'MOGCSP PMU',
    leadMinistry: 'MOGCSP',
    formula: 'computeSasaSessionAttendance',
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'LWEP-OUT-C2-02',
    name: 'Number of GBV cases receiving service through LWEP-supported entry points',
    description: 'Count of GBV cases that received at least one service through an LWEP-supported facility.',
    framework: 'LWEP',
    area: 'Component 2',
    unit: 'count',
    periodicity: 'QUARTERLY',
    disaggregations: ['LOCATION'],
    custodianAgency: 'MOGCSP PMU',
    leadMinistry: 'MOGCSP',
    formula: 'computeGbvCasesWithService',
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'LWEP-OUT-C3-01',
    name: 'Number of women receiving livelihood grants',
    description: 'Count of women beneficiaries who have received at least one livelihood grant disbursement.',
    framework: 'LWEP',
    area: 'Component 3',
    unit: 'count',
    periodicity: 'QUARTERLY',
    disaggregations: ['LOCATION'],
    custodianAgency: 'MOGCSP PMU',
    leadMinistry: 'MOGCSP',
    formula: 'computeLivelihoodGrantRecipients',
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
  {
    code: 'LWEP-OUT-C5-01',
    name: 'Data-completeness rate of the GB MIS across the six counties',
    description: 'Percentage of expected monthly indicator values that are populated with verified or provisional data.',
    framework: 'LWEP',
    area: 'Component 5',
    unit: '%',
    periodicity: 'MONTHLY',
    disaggregations: ['LOCATION'],
    custodianAgency: 'MOGCSP PMU',
    leadMinistry: 'MOGCSP',
    formula: 'computeDataCompletenessRate',
    dhis2DataElementId: null,
    dhis2CategoryComboId: null,
    active: true,
  },
];
