export const Role = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  SUPERVISOR: 'SUPERVISOR',
  CASE_WORKER: 'CASE_WORKER',
  DATA_ENTRY_CLERK: 'DATA_ENTRY_CLERK',
  ANALYST: 'ANALYST',
  VIEWER: 'VIEWER',
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const SpecialAttribute = {
  DPO: 'DPO',
  M_AND_E_OFFICER: 'M_AND_E_OFFICER',
  CHILD_PROTECTION_LEAD: 'CHILD_PROTECTION_LEAD',
  COMPLIANCE_AUDITOR: 'COMPLIANCE_AUDITOR',
} as const;

export type SpecialAttribute = (typeof SpecialAttribute)[keyof typeof SpecialAttribute];

export const UserStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DISABLED: 'DISABLED',
} as const;

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];

export const Permission = {
  // Cases
  CASE_LIST: 'CASE_LIST',
  CASE_READ: 'CASE_READ',
  CASE_CREATE: 'CASE_CREATE',
  CASE_UPDATE: 'CASE_UPDATE',
  CASE_CLOSE: 'CASE_CLOSE',
  CASE_ASSIGN: 'CASE_ASSIGN',
  CASE_SUPERVISOR_REVIEW: 'CASE_SUPERVISOR_REVIEW',
  CASE_CROSS_ORG_GRANT: 'CASE_CROSS_ORG_GRANT',
  CASE_EXPORT_AGGREGATE: 'CASE_EXPORT_AGGREGATE',

  // Beneficiaries
  BENEFICIARY_LIST: 'BENEFICIARY_LIST',
  BENEFICIARY_READ: 'BENEFICIARY_READ',
  BENEFICIARY_CREATE: 'BENEFICIARY_CREATE',
  BENEFICIARY_UPDATE: 'BENEFICIARY_UPDATE',
  BENEFICIARY_WITHDRAW: 'BENEFICIARY_WITHDRAW',
  BENEFICIARY_CONSENT_MANAGE: 'BENEFICIARY_CONSENT_MANAGE',
  BENEFICIARY_GRANT_RECORD: 'BENEFICIARY_GRANT_RECORD',
  BENEFICIARY_EXPORT: 'BENEFICIARY_EXPORT',

  // Sessions & VSLAs
  SESSION_MANAGE: 'SESSION_MANAGE',
  SESSION_ATTENDANCE: 'SESSION_ATTENDANCE',
  VSLA_MANAGE: 'VSLA_MANAGE',

  // Indicators
  INDICATOR_CATALOG_VIEW: 'INDICATOR_CATALOG_VIEW',
  INDICATOR_VALUE_VIEW_VERIFIED: 'INDICATOR_VALUE_VIEW_VERIFIED',
  INDICATOR_VALUE_VIEW_UNVERIFIED: 'INDICATOR_VALUE_VIEW_UNVERIFIED',
  INDICATOR_VALUE_ENTER: 'INDICATOR_VALUE_ENTER',
  INDICATOR_VALUE_APPROVE: 'INDICATOR_VALUE_APPROVE',
  INDICATOR_RECOMPUTE: 'INDICATOR_RECOMPUTE',
  INDICATOR_CATALOG_MANAGE: 'INDICATOR_CATALOG_MANAGE',
  INDICATOR_TARGET_EDIT: 'INDICATOR_TARGET_EDIT',
  INDICATOR_EXPORT: 'INDICATOR_EXPORT',

  // Dashboard
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  // User management
  USER_CREATE: 'USER_CREATE',
  USER_GRANT_SUPER_ADMIN: 'USER_GRANT_SUPER_ADMIN',
  USER_GRANT_ADMIN: 'USER_GRANT_ADMIN',
  USER_GRANT_ELEVATED: 'USER_GRANT_ELEVATED',
  USER_GRANT_BASIC: 'USER_GRANT_BASIC',
  USER_SUSPEND: 'USER_SUSPEND',
  USER_FORCE_RESET: 'USER_FORCE_RESET',
  USER_DEVICE_WIPE: 'USER_DEVICE_WIPE',
  USER_AUDIT_VIEW: 'USER_AUDIT_VIEW',

  // Config & integration
  INTEGRATION_VIEW: 'INTEGRATION_VIEW',
  INTEGRATION_EDIT: 'INTEGRATION_EDIT',
  INTEGRATION_TEST: 'INTEGRATION_TEST',
  FEATURE_FLAG_TOGGLE: 'FEATURE_FLAG_TOGGLE',
  KEY_ROTATE: 'KEY_ROTATE',

  // Secondary data (ETL ingestion)
  SECONDARY_DATA_VIEW: 'SECONDARY_DATA_VIEW',
  SECONDARY_DATA_MANAGE: 'SECONDARY_DATA_MANAGE',

  // Audit
  AUDIT_VIEW_ALL: 'AUDIT_VIEW_ALL',
  AUDIT_VIEW_OWN_SCOPE: 'AUDIT_VIEW_OWN_SCOPE',
  AUDIT_EXPORT: 'AUDIT_EXPORT',
  DSR_PROCESS: 'DSR_PROCESS',
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

export type PermissionMap = Record<Role, ReadonlySet<Permission>>;
