import type {
  IndicatorFramework,
  Periodicity,
  Disaggregation,
  QualityFlag,
} from '@gb-mis/types';

export interface IndicatorMeta {
  code: string;
  name: string;
  description: string;
  framework: IndicatorFramework;
  area: string;
  unit: string;
  periodicity: Periodicity;
  disaggregations: Disaggregation[];
  custodianAgency: string;
  leadMinistry: string;
  formula: string | null;
  dhis2DataElementId: string | null;
  dhis2Sync: boolean;
  defaultQualityFlag: QualityFlag;
  sdgTarget: string | null;
  notes: string | null;
}

// The catalog is the human-readable source of truth.
// The database Indicator table is seeded from packages/db/seed/indicators.ts,
// which derives its content from this same source.
// Codes are permanent — never reuse a retired code.

export const INDICATOR_CATALOG: ReadonlyMap<string, IndicatorMeta> = new Map([
  // ── LWEP 22-indicator minimum set ─────────────────────────────────────────

  // Representation (5)
  ['BPfA-REP-001', {
    code: 'BPfA-REP-001',
    name: 'Percentage of seats held by women in national parliament',
    description: 'Share of seats in the national parliament occupied by women.',
    framework: 'BPFA',
    area: 'Representation',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'IPU / UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '5.5.1',
    notes: 'Source: IPU Parline database + Liberia NEC. DHIS2 mapping pending Inception phase.',
  }],

  ['BPfA-REP-002', {
    code: 'BPfA-REP-002',
    name: 'Percentage of women in ministerial positions',
    description: 'Share of cabinet/ministerial positions occupied by women.',
    framework: 'BPFA',
    area: 'Representation',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '5.5.1',
    notes: 'Source: UN Women Global Database on Women in Politics.',
  }],

  ['BPfA-REP-003', {
    code: 'BPfA-REP-003',
    name: 'Percentage of women in leadership positions in media organisations',
    description: 'Share of senior editorial and management positions in media held by women.',
    framework: 'BPFA',
    area: 'Representation',
    unit: '%',
    periodicity: 'BIENNIAL',
    disaggregations: [],
    custodianAgency: 'MOGCSP',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: null,
    notes: 'Source: Liberia Media Development Report (biennial).',
  }],

  ['BPfA-REP-004', {
    code: 'BPfA-REP-004',
    name: 'Percentage of women in local councils / leadership positions in municipalities',
    description: 'Share of local council seats and municipal leadership held by women.',
    framework: 'BPFA',
    area: 'Representation',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'MOGCSP',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '5.5.1',
    notes: 'Source: Local Government Act Implementation Report.',
  }],

  ['BPfA-REP-005', {
    code: 'BPfA-REP-005',
    name: 'Percentage of women leaders in civil-society organisations',
    description: 'Share of executive director and board chair positions in CSOs held by women.',
    framework: 'BPFA',
    area: 'Representation',
    unit: '%',
    periodicity: 'BIENNIAL',
    disaggregations: [],
    custodianAgency: 'MOGCSP',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: null,
    notes: 'Source: Liberia CSO Report (biennial).',
  }],

  // Education (4)
  ['BPfA-EDU-001', {
    code: 'BPfA-EDU-001',
    name: 'Net enrolment rate for girls in primary education',
    description: 'Percentage of girls of primary-school age who are enrolled in primary school.',
    framework: 'BPFA',
    area: 'Education',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'UIS / UNESCO',
    leadMinistry: 'MoE',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '4.1.2',
    notes: 'Source: MoE EMIS, UNESCO UIS.',
  }],

  ['BPfA-EDU-002', {
    code: 'BPfA-EDU-002',
    name: 'Percentage of girls completing secondary education',
    description: 'Completion rate for girls in lower and upper secondary education.',
    framework: 'BPFA',
    area: 'Education',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'UIS / UNESCO',
    leadMinistry: 'MoE',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '4.1.2',
    notes: 'Source: MoE EMIS, UNICEF.',
  }],

  ['BPfA-EDU-003', {
    code: 'BPfA-EDU-003',
    name: 'Adult female literacy rate',
    description: 'Percentage of women 15 years and older who can read and write.',
    framework: 'BPFA',
    area: 'Education',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['AGE', 'LOCATION'],
    custodianAgency: 'UIS / UNESCO',
    leadMinistry: 'MoE',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '4.6.2',
    notes: 'Source: UNESCO, LISGIS HIES (every 5 years).',
  }],

  ['BPfA-EDU-004', {
    code: 'BPfA-EDU-004',
    name: 'Percentage of women enrolled in STEM programs in tertiary education',
    description: 'Share of women among students enrolled in science, technology, engineering and mathematics tertiary programmes.',
    framework: 'BPFA',
    area: 'Education',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'UIS / UNESCO',
    leadMinistry: 'MoE',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: null,
    notes: 'Source: MoE higher-education institutional returns.',
  }],

  // Work (2)
  ['BPfA-WRK-001', {
    code: 'BPfA-WRK-001',
    name: 'Female labour-force participation rate',
    description: 'Proportion of women 15+ who are in the labour force (employed or actively seeking employment).',
    framework: 'BPFA',
    area: 'Work',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['AGE', 'LOCATION'],
    custodianAgency: 'ILO',
    leadMinistry: 'MoL',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '8.5',
    notes: 'Source: ILO modelled estimates, LISGIS Labour Force Survey.',
  }],

  ['BPfA-WRK-002', {
    code: 'BPfA-WRK-002',
    name: 'Gender wage gap',
    description: 'Difference between male and female median wages expressed as a percentage of male median wages.',
    framework: 'BPFA',
    area: 'Work',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'ILO',
    leadMinistry: 'MoL',
    formula: 'computeGenderWageGap',
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '8.5.1',
    notes: 'Source: ILO modelled estimates, LISGIS LFS. Formula: (maleMedianWage - femaleMedianWage) / maleMedianWage × 100.',
  }],

  // Health (3)
  ['BPfA-HLT-001', {
    code: 'BPfA-HLT-001',
    name: 'Maternal mortality ratio',
    description: 'Number of maternal deaths per 100,000 live births.',
    framework: 'BPFA',
    area: 'Health',
    unit: 'per 100,000 live births',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'WHO / UNICEF / UNFPA',
    leadMinistry: 'MoH',
    formula: 'computeMmrPer100k',
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '3.1.1',
    notes: 'Numerator: maternal deaths. Denominator: live births. Source: LISGIS DHS or MoH DHIS2. DHIS2 mapping pending Inception phase.',
  }],

  ['BPfA-HLT-002', {
    code: 'BPfA-HLT-002',
    name: 'Contraceptive prevalence rate (modern methods)',
    description: 'Percentage of women 15–49 in union who are using modern contraceptive methods.',
    framework: 'BPFA',
    area: 'Health',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['AGE', 'LOCATION'],
    custodianAgency: 'UNPD / UNFPA',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '3.7.1',
    notes: 'Source: LISGIS DHS (every 5 years).',
  }],

  ['BPfA-HLT-003', {
    code: 'BPfA-HLT-003',
    name: 'Percentage of women aged 20–24 married before age 18',
    description: 'Proportion of women aged 20–24 who were first married or in union before age 18.',
    framework: 'BPFA',
    area: 'Health',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['LOCATION'],
    custodianAgency: 'UNICEF',
    leadMinistry: 'MoH',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '5.3.1',
    notes: 'Source: LISGIS DHS, UNICEF MICS.',
  }],

  // Violence / GBV (1)
  ['BPfA-GBV-001', {
    code: 'BPfA-GBV-001',
    name: 'Prevalence of physical or sexual violence against women',
    description: 'Proportion of women who experienced physical or sexual violence in the last 12 months.',
    framework: 'BPFA',
    area: 'Violence',
    unit: '%',
    periodicity: 'EVERY_5Y',
    disaggregations: ['AGE', 'LOCATION'],
    custodianAgency: 'WHO / UNSD / UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '5.2.1',
    notes: 'Primary source: LISGIS DHS every 5 years. LWEP case data is secondary and not population-representative.',
  }],

  // WASH (1)
  ['BPfA-WSH-001', {
    code: 'BPfA-WSH-001',
    name: 'Percentage of women with access to safe drinking water and improved sanitation facilities',
    description: 'Share of women in households with access to safely managed drinking water and improved sanitation.',
    framework: 'BPFA',
    area: 'WASH',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'WHO / UNICEF JMP',
    leadMinistry: 'MoA',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '6.1.1',
    notes: 'Source: Water and Sanitation Sector Performance Report. SDG links: 6.1.1 and 6.2.1.',
  }],

  // Agriculture & Environment (3)
  ['BPfA-AGR-001', {
    code: 'BPfA-AGR-001',
    name: 'Percentage of women with land ownership rights',
    description: 'Share of women who own or have secure rights over agricultural land.',
    framework: 'BPFA',
    area: 'Agriculture',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: ['LOCATION'],
    custodianAgency: 'FAO',
    leadMinistry: 'MoA',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '5.a.1',
    notes: 'Source: Liberia Land Authority administrative data.',
  }],

  ['BPfA-AGR-002', {
    code: 'BPfA-AGR-002',
    name: 'Percentage of women involved in decision-making in agricultural cooperatives',
    description: 'Share of women in leadership and decision-making roles within registered agricultural cooperatives.',
    framework: 'BPFA',
    area: 'Agriculture',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'FAO',
    leadMinistry: 'MoA',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '5.a',
    notes: 'Source: MoA cooperatives registry.',
  }],

  ['BPfA-ENV-001', {
    code: 'BPfA-ENV-001',
    name: 'Percentage of women involved in environmental conservation programs',
    description: 'Share of women participating in government-registered environmental conservation programs.',
    framework: 'BPFA',
    area: 'Environment',
    unit: '%',
    periodicity: 'BIENNIAL',
    disaggregations: [],
    custodianAgency: 'MOGCSP',
    leadMinistry: 'MoA',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: null,
    notes: 'Source: Liberia EPA program registrations (biennial).',
  }],

  // Security (1)
  ['BPfA-SEC-001', {
    code: 'BPfA-SEC-001',
    name: 'Percentage of women in military or police peacekeeping forces',
    description: 'Share of women personnel in the Liberia National Police and Armed Forces of Liberia, including UN peacekeeping deployments.',
    framework: 'BPFA',
    area: 'Security',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'UNODC',
    leadMinistry: 'MoD',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '5.5',
    notes: 'Source: MoJ and MoD reports, UNODC data.',
  }],

  // Maputo Protocol additions (2)
  ['MAPUTO-REP-001', {
    code: 'MAPUTO-REP-001',
    name: 'Percentage of women in national parliament (Maputo reporting frame)',
    description: 'Share of seats in the national parliament held by women, reported under the AU Maputo Protocol monitoring framework.',
    framework: 'MAPUTO',
    area: 'Representation',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'AU / UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '5.5.1',
    notes: 'Source: World Bank Gender Data Portal. Parallel to BPfA-REP-001 for AU reporting obligations.',
  }],

  ['MAPUTO-DM-001', {
    code: 'MAPUTO-DM-001',
    name: 'Percentage of women in senior / decision-making positions (public or private sector)',
    description: 'Share of women in senior management and executive positions across public and private sector organisations.',
    framework: 'MAPUTO',
    area: 'Decision-Making',
    unit: '%',
    periodicity: 'ANNUAL',
    disaggregations: [],
    custodianAgency: 'UN Women',
    leadMinistry: 'MOGCSP',
    formula: null,
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'UNVERIFIED',
    sdgTarget: '5.5.2',
    notes: 'Source: MOGCSP biennial survey of public institutions and registered private companies.',
  }],

  // ── LWEP internal output indicators ───────────────────────────────────────
  ['LWEP-OUT-C1-01', {
    code: 'LWEP-OUT-C1-01',
    name: 'Number of communities reached with SASA! social norms engagement',
    description: 'Count of communities with at least one completed SASA! session.',
    framework: 'LWEP',
    area: 'Component 1',
    unit: 'count',
    periodicity: 'QUARTERLY',
    disaggregations: ['LOCATION'],
    custodianAgency: 'MOGCSP PMU',
    leadMinistry: 'MOGCSP',
    formula: 'computeCommunitiesWithSasaSessions',
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'PROVISIONAL',
    sdgTarget: null,
    notes: 'Computed from CommunitySession records. Not synced to DHIS2 — internal LWEP reporting only.',
  }],

  ['LWEP-OUT-C3-01', {
    code: 'LWEP-OUT-C3-01',
    name: 'Number of women receiving livelihood grants',
    description: 'Count of unique female beneficiaries with at least one DISBURSED livelihood grant.',
    framework: 'LWEP',
    area: 'Component 3',
    unit: 'count',
    periodicity: 'QUARTERLY',
    disaggregations: ['LOCATION'],
    custodianAgency: 'MOGCSP PMU',
    leadMinistry: 'MOGCSP',
    formula: 'computeLivelihoodGrantRecipients',
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'PROVISIONAL',
    sdgTarget: null,
    notes: 'Computed from LivelihoodGrant records. LWEP internal reporting only.',
  }],

  ['LWEP-OUT-C5-01', {
    code: 'LWEP-OUT-C5-01',
    name: 'Data-completeness rate of the GB MIS across the six counties',
    description: 'Percentage of expected monthly indicator values populated with verified or provisional data.',
    framework: 'LWEP',
    area: 'Component 5',
    unit: '%',
    periodicity: 'MONTHLY',
    disaggregations: ['LOCATION'],
    custodianAgency: 'MOGCSP PMU',
    leadMinistry: 'MOGCSP',
    formula: 'computeDataCompletenessRate',
    dhis2DataElementId: null,
    dhis2Sync: false,
    defaultQualityFlag: 'PROVISIONAL',
    sdgTarget: null,
    notes: 'System-computed. Covers the 22 minimum-set indicators only.',
  }],
]);

export function getIndicator(code: string): IndicatorMeta | undefined {
  return INDICATOR_CATALOG.get(code);
}

export function getIndicatorsByFramework(framework: IndicatorFramework): IndicatorMeta[] {
  return Array.from(INDICATOR_CATALOG.values()).filter(
    (ind) => ind.framework === framework,
  );
}

export function getDhis2SyncableIndicators(): IndicatorMeta[] {
  return Array.from(INDICATOR_CATALOG.values()).filter((ind) => ind.dhis2Sync);
}
